### ISSUE TITLE
New notes are not registered in the server as html

### ISSUE THREAD

**Issue by goktug97** [goktug97/org-roam-graph-server#1]
New notes are not registered for preview because initialization of servlets are done while the mode is initializing.

A hook should be added to find file to initialize new servlets.

**Comment by goktug97** [comment]
Fixed https://github.com/goktug97/org-roam-graph-server/commit/38c8677a77107cc409f4fb6d3dbe7b8021012af2

**Comment by husnoo** [comment]
This problem came back - the only way to update the html-hover preview is to reload emacs entirely. I had a quick look at the code, but it's changed an enormous amount from then and now, and I'm just starting out with emacs... The File Viewer tab is also always empty - could it be related at all?

**Comment by goktug97** [comment]
I tried with the latest org-roam and org-roam-server. 
- Start org-roam-server
- Open 127.0.0.1:8080 (Not an opened one from an old session)
- Create a note
- Create a second note with a connection to the previous note.
- Check graph and file view.

Result:
Without a refresh:
The first note and second note is added to the graph with a connection between them. Notes are registered in file viewer page. 

Are you creating the notes using the functions provided by the org-roam? Because registering new notes in org-roam-server is hooked to those functions.

**Comment by husnoo** [comment]
Sorry if I'm hot very adept with emacs yet, only just started digging below the surface! I'm using:

```
 Emacs: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13)
  org-roam           20200903.202  installed             Roam Research replica with Org-mode
  org-roam-server    20200822.1054 installed             Org Roam Database Visualizer
```
This is the minimum .emacs I'm using for this:
```
(package-initialize)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(require 'package)
(setq org-roam-directory "~/data/markor")
(add-hook 'after-init-hook 'org-roam-mode)

(custom-set-variables
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["black" "#d55e00" "#009e73" "#f8ec59" "#0072b2" "#cc79a7" "#56b4e9" "white"])
 '(column-number-mode t)
 '(custom-enabled-themes (quote (deeper-blue)))
 '(fringe-mode (quote (1 . 1)) nil (fringe))
 '(inhibit-startup-screen t)
 '(org-roam-capture-templates
   (quote
    (("d" "default" plain
      (function org-roam-capture--get-point)
      "%?" :file-name "%<%Y%m%d%H%M%S>-${slug}" :head "#+title: ${title}
#+roam_alias:

" :unnarrowed t))))
 '(org-roam-directory "~/data/markor")
 '(org-roam-mode t nil (org-roam))
 '(org-roam-server-mode t)
 '(org-roam-server-port 9000)
 '(org-roam-server-serve-files t)
 '(org-startup-truncated nil)
 '(package-selected-packages
   (quote
    (org-roam-server org-edit-latex free-keys org-roam org)))
 '(server-mode t)
 '(show-paren-mode t)
 '(speedbar-show-unknown-files t)
 '(window-divider-default-bottom-width 4)
 '(window-divider-default-right-width 2))

(global-set-key "\M-f" 'org-roam-find-file)
(global-set-key "\M-i" 'org-roam-insert)
(global-set-key "\M-r" 'org-roam)
(global-set-key "\M-g" 'org-roam-graph)

(require 'org-protocol)
(require 'org-roam-protocol)
```

If I create a new note using M-F and then M-x org-roam-db-build-cache, and then refresh the page in Chromium, enable preview, the preview reads "Not Found The requested URL was not found on this server."

**Comment by goktug97** [comment]
Can you evaluate
```elisp
(require `org-roam-server)
org-capture-after-finalize-hook
```
It should print a list of functions in the minibuffer. Can you check whether `org-roam-server-capture-servlet` is present in that list or not.  If it is present can you do `M-x debug-on-entry RET org-roam-server-capture-servlet RET`, create a new note using `M-f`, and finish capture with `C-c C-c`. A window should pop up with a traceback. Can you copy paste it here. I don't think there is a problem with that function because it would throw an error if it is executed with an error.

**Comment by husnoo** [comment]
```
(New file)
Saving file /home/nawal/data/markor/20200905141435-test.org...
Wrote /home/nawal/data/markor/20200905141435-test.org
Entering debugger...
(org-roam) database updated during idle: 20200905141435-test.org.
Back to top level
```
Thanks for helping with this! Still same problem at this point - the html isn't found for hover/preview.

**Comment by goktug97** [comment]
Can you remove ` '(org-roam-server-mode t)` from your config?  If you wan't to start org-roam-server on start you should call it with as a function `(org-roam-server-mode 1)`. Hopefully this will work.

**Comment by husnoo** [comment]
Hah that did work!! Thanks so much! Can't get the file viewer to work still, should I open another thread?

**Comment by goktug97** [comment]
You restarted the emacs, the browser and when you add a new note, it still shows `File not found` ?

**Comment by husnoo** [comment]
The preview on hover works now, thanks to your suggestion with starting the server. It's when I click on File Viewer that it is completely empty.

**Comment by husnoo** [comment]
Actually the error might be on the js side now - when I go to the browser console it says this when I refresh the page:
```
vis-network.min.js:85 Uncaught Error: Unknown dataType
    at e.value (vis-network.min.js:85)
    at updateNodesAndEdges ((index):718)
    at update ((index):505)
    at Object.success ((index):471)
    at c (jquery-3.5.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.5.0.min.js:2)
    at l (jquery-3.5.0.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.5.0.min.js:2)
```

**Comment by husnoo** [comment]
The files exist - going to their page:
http://127.0.0.1:9000/20200905150213-emacs_lisp.html?token=null works. It's
the "File Viewer" (really, directory list) that's not loading for some
reason.

**Comment by goktug97** [comment]
Can you check your browser's developer console for any error that shows up when you click to the `File Viewer`

**Comment by husnoo** [comment]
Yes it's only the error as above, https://github.com/org-roam/org-roam-server/issues/1#issuecomment-687612042, i.e. "Unknown dataType" when I load the page 127.0.0.1:9000, then clicking on File Viewer doesn't do anything at all, not even new errors. So presumably there's some processing that's stopped and then File Viewer can't do anything?

The error message from vis isn't helpful as it doesn't say which part of your JS code is being run and where it's stopped. I'll try to put some console.log() to find out where it's stopping. I've tried Chrome (83.0.4103.14 (Official Build) beta (64-bit)), Chromium(Version 81.0.4044.122 (Developer Build) (64-bit))
, and Firefox (75.0 (64-bit)).

**Comment by goktug97** [comment]
To test, can you set `org-roam-server-serve-files` to `nil`

**Comment by husnoo** [comment]
What would you expect that to do? I can't tell if it made any difference.

Anyway the error above, with the datatype, was due to edgeDataset.update(roamData.edges); choking on a repository without edges. Adding an edge fixed that - but the file viewer is still empty.

**Comment by husnoo** [comment]
No sorry, that works too now! Woo! Thank you so much! Do you have a Patreon or anything I can buy you a beer?

**Comment by goktug97** [comment]
I am awere of that problem no edge breaks it but I thought, they will have an edge in their graph at some point so the problem will vanish and then I forgot about the problem :D 

> No sorry, that works too now! Woo! Thank you so much! Do you have a Patreon or anything I can buy you a beer?

Thank you for the kind offer!! But a thank you is enough :)
